name: Validate Packer Configuration
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Validate Packer Configuration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress codebase
        run:  touch webapp.tar.gz && tar --exclude=webapp.tar.gz --exclude='.git' --exclude='.github' --exclude='.vscode' --exclude='node_modules' --exclude="package-lock.json" --exclude=".env" -zcvf webapp.tar.gz .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: packer init -var-file="./packer/variables.pkrvars.hcl" ./packer/

      - name: Run `packer validate`
        id: validate
        run: packer validate -var-file="./packer/variables.pkrvars.hcl" ./packer/